# Generated by Django 4.0.3 on 2022-03-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quizzes_results_questions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.options')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.questions')),
            ],
        ),
    ]
