# Generated by Django 4.0.3 on 2022-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='option_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(default='Answer', max_length=200, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default='Option1', max_length=200, verbose_name='Option 1'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default='Option2', max_length=200, verbose_name='Option 2'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default='Option3', max_length=200, verbose_name='Option 3'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(default='Option4', max_length=200, verbose_name='Option 4'),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
