# Generated by Django 4.0.3 on 2022-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_questions_answer_delete_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='mark_correct',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='mark_wrong',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='mark_for_correct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='mark_for_wrong',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(choices=[('', 'Select'), ('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default='Select', max_length=200),
        ),
    ]
