# Generated by Django 4.0.3 on 2022-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_quizzes_mark_for_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='mark_for_correct',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='mark_for_wrong',
            field=models.FloatField(),
        ),
    ]
