# Generated by Django 4.0.3 on 2022-03-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_quizzes_mark_for_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(max_length=200, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(max_length=200, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(max_length=200, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.CharField(max_length=200, verbose_name='Option 4'),
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('feedback', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Date Posted')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
