# Generated by Django 4.0.3 on 2022-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_questions_option1_alter_questions_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='users.users'),
        ),
    ]
