# Generated by Django 4.0.3 on 2022-04-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_no',
            field=models.IntegerField(default=0),
        ),
    ]
