# Generated by Django 4.0.3 on 2022-04-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_questions_question_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'ordering': ('-date',)},
        ),
    ]
