# Generated by Django 4.0.3 on 2022-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_results_candidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateField(verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='date_added',
            field=models.DateField(verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='results',
            name='candidate_id',
            field=models.CharField(max_length=100, verbose_name='Candidate Id'),
        ),
        migrations.AlterField(
            model_name='results',
            name='date',
            field=models.DateField(verbose_name='Date Attended'),
        ),
    ]
