# Generated by Django 4.0.3 on 2022-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_feedbacks_date_alter_quizzes_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateTimeField(verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='results',
            name='date',
            field=models.DateTimeField(verbose_name='Date Attended'),
        ),
    ]
