# Generated by Django 4.0.3 on 2022-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_feedbacks_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='status',
            field=models.CharField(blank=True, max_length=10, verbose_name='Status'),
        ),
    ]
