# Generated by Django 4.0.3 on 2022-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_feedbacks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='reply_status',
            field=models.CharField(blank=True, max_length=10, verbose_name='Reply Status'),
        ),
    ]
