# Generated by Django 4.0.3 on 2022-04-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_feedbacks_reply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=10, verbose_name='To')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('status', models.IntegerField()),
            ],
        ),
    ]
