# Generated by Django 4.0.3 on 2022-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
