# Generated by Django 4.0.3 on 2022-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_users_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=100, verbose_name='Candidate Id')),
                ('question_no', models.IntegerField(default=0)),
                ('selected_option', models.CharField(max_length=10, verbose_name='Option selected by user')),
            ],
        ),
    ]
