# Generated by Django 4.0.3 on 2022-05-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_quizlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='not_activated', max_length=20),
        ),
    ]
